# Generated by Django 5.1.2 on 2025-02-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
