# Generated by Django 5.1.2 on 2025-02-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrequest',
            name='reason',
            field=models.TextField(default='None'),
        ),
    ]
