# Generated by Django 5.1.2 on 2025-02-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_vacationrequest_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_num',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
